export default [
	{
		id: '1',
		slug: 'population-zero',
		title: 'Population Zero',
		developer: 'Rockstar Games',
		img: 'https://source.unsplash.com/user/willianjusten/300x140',
		price: 235,
		promotionalPrice: 215,
	},
	{
		id: '2',
		slug: 'population-zero',
		title: 'Population Zero',
		developer: 'Rockstar Games',
		img: 'https://source.unsplash.com/user/willianjusten/300x140',
		price: 235,
		promotionalPrice: 215,
	},
	{
		id: '3',
		slug: 'population-zero',
		title: 'Population Zero',
		developer: 'Rockstar Games',
		img: 'https://source.unsplash.com/user/willianjusten/300x140',
		price: 235,
		promotionalPrice: 215,
	},
	{
		id: '4',
		slug: 'population-zero',
		title: 'Population Zero',
		developer: 'Rockstar Games',
		img: 'https://source.unsplash.com/user/willianjusten/300x140',
		price: 235,
		promotionalPrice: 215,
	},
	{
		id: '5',
		slug: 'population-zero',
		title: 'Population Zero',
		developer: 'Rockstar Games',
		img: 'https://source.unsplash.com/user/willianjusten/300x140',
		price: 235,
		promotionalPrice: 215,
	},
	{
		id: '6',
		slug: 'population-zero',
		title: 'Population Zero',
		developer: 'Rockstar Games',
		img: 'https://source.unsplash.com/user/willianjusten/300x140',
		price: 235,
		promotionalPrice: 215,
	},
	{
		id: '7',
		slug: 'population-zero',
		title: 'Population Zero',
		developer: 'Rockstar Games',
		img: 'https://source.unsplash.com/user/willianjusten/300x140',
		price: 235,
		promotionalPrice: 215,
	},
];